/**
 * TruCare Icon Library Manifest
 *
 * Curated subset of Lucide icons organized by category for use across
 * the TruCare application. All icons are available via `lucide-react`.
 *
 * Usage:
 *   import { Home, ArrowLeft } from "lucide-react"
 *
 * This manifest serves as the canonical reference for which icons are
 * approved for use in the design system.
 */

export const iconLibrary = {
  navigation: [
    "Home",
    "ArrowLeft",
    "ArrowRight",
    "ChevronDown",
    "ChevronUp",
    "ChevronLeft",
    "ChevronRight",
    "Menu",
    "X",
    "Search",
    "Filter",
    "ExternalLink",
    "MoreHorizontal",
    "MoreVertical",
    "ArrowUpDown",
  ],
  actions: [
    "Plus",
    "Edit",
    "Trash2",
    "Download",
    "Upload",
    "Copy",
    "Save",
    "Send",
    "Share2",
    "RefreshCw",
    "Check",
    "Eye",
    "EyeOff",
    "Lock",
    "Unlock",
    "Settings",
    "Sliders",
    "Power",
    "RotateCcw",
    "Undo2",
  ],
  status: [
    "CheckCircle",
    "XCircle",
    "AlertCircle",
    "AlertTriangle",
    "Info",
    "Clock",
    "Loader2",
    "Ban",
    "ShieldCheck",
    "CircleDot",
    "CircleCheck",
    "Timer",
  ],
  communication: [
    "Mail",
    "Phone",
    "MessageSquare",
    "Bell",
    "AtSign",
    "Inbox",
    "Send",
    "MessageCircle",
    "Voicemail",
    "PhoneCall",
  ],
  files: [
    "File",
    "FileText",
    "FilePlus",
    "Files",
    "Folder",
    "FolderOpen",
    "Paperclip",
    "Image",
    "Receipt",
    "FileCheck",
    "FileX",
    "FileSearch",
  ],
  users: [
    "User",
    "Users",
    "UserPlus",
    "UserCheck",
    "UserX",
    "Contact",
    "CircleUser",
    "UserCog",
  ],
  healthcare: [
    "Heart",
    "HeartPulse",
    "Activity",
    "Stethoscope",
    "Pill",
    "Syringe",
    "ClipboardList",
    "ClipboardCheck",
    "ClipboardX",
    "Shield",
    "ShieldCheck",
    "ShieldAlert",
    "Scan",
    "Fingerprint",
    "CreditCard",
    "DollarSign",
    "Receipt",
    "Calculator",
    "BarChart3",
    "Thermometer",
    "Brain",
    "Bone",
    "Eye",
    "Ear",
    "Baby",
    "Ambulance",
    "Hospital",
    "Cross",
    "BadgeCheck",
    "Scale",
  ],
  layout: [
    "LayoutDashboard",
    "LayoutList",
    "LayoutGrid",
    "Table",
    "Columns3",
    "PanelLeft",
    "PanelRight",
    "PanelTop",
    "Maximize2",
    "Minimize2",
    "SplitSquareHorizontal",
    "GripVertical",
    "GripHorizontal",
    "Rows3",
    "Kanban",
  ],
  dateTime: [
    "Calendar",
    "CalendarDays",
    "CalendarCheck",
    "CalendarX",
    "Clock",
    "Timer",
    "History",
    "CalendarRange",
  ],
  data: [
    "BarChart3",
    "LineChart",
    "PieChart",
    "TrendingUp",
    "TrendingDown",
    "Hash",
    "Database",
    "HardDrive",
    "Server",
    "Gauge",
  ],
  misc: [
    "Zap",
    "Star",
    "Bookmark",
    "Tag",
    "Flag",
    "Globe",
    "Link",
    "Link2",
    "Sparkles",
    "Lightbulb",
  ],
} as const satisfies Record<string, readonly string[]>

export type IconCategory = keyof typeof iconLibrary
